services:
  custom_http_connect:
    build: .
    image: custom_http_connect
    environment:
      TZ: Asia/Irkutsk

      PARTNERAPI_HTTP_TIMEOUT: 30
      PARTNERAPI_HTTP_RETRIES_COUNT: 3
      PARTNERAPI_HTTP_RETRIES_SLEEP: 30

      PARTNERAPI_HTTP_TIMEOUT_ORDER: 10
      PARTNERAPI_HTTP_RETRIES_COUNT_ORDER: 1
      PARTNERAPI_HTTP_RETRIES_SLEEP_ORDER: 0
      
      PARTNERAPI_URL: ''
  
      PARTNERAPI_RABBITMQ_TIMEOUT: 100
      PARTNERAPI_RABBITMQ_RETRIES_COUNT: 3
      PARTNERAPI_RABBITMQ_RETRIES_SLEEP: 30
  
      PARTNERAPI_SOURCE_PROJECT_ID: 2
      PARTNERAPI_KODPOST: 1122
  
      PARTNERAPI_METRICS_PORT: 23241
